title: The Fellow Gamer Podcast
description: You'll hear me talk about amazing things!
author: LTG Podcast Network
email: tfgp@ltg.link
lang: en-us
copyright: "&#xA9;2022 LTG Network. All rights reserved."
logo: /assets/img/logo.jpg
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
